// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motos.Infraestructure.Data.AppData;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Motos.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Motos.Domain.Entities.EventoMoto", b =>
                {
                    b.Property<string>("IdEventoMoto")
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<DateTime>("DataHoraEvento")
                        .HasColumnType("TIMESTAMP");

                    b.Property<bool>("EventoVisualizado")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("IdEvento")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<string>("IdMoto")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)");

                    b.HasKey("IdEventoMoto");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdMoto");

                    b.ToTable("TB_EVENTO_MOTO");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.EstruturaPatio", b =>
                {
                    b.Property<string>("IdPatio")
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<decimal>("CoordenadaXEstrutura")
                        .HasColumnType("NUMBER");

                    b.Property<decimal>("CoordenadaYEstrutura")
                        .HasColumnType("NUMBER");

                    b.Property<decimal>("RotacaoEstrutura")
                        .HasColumnType("NUMBER");

                    b.Property<decimal>("TamanhoEstrutura")
                        .HasColumnType("NUMBER");

                    b.HasKey("IdPatio");

                    b.ToTable("TB_ESTRUTURA_PATIO");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.Evento", b =>
                {
                    b.Property<string>("IdEvento")
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<string>("CorEvento")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("DescricaoEvento")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)");

                    b.HasKey("IdEvento");

                    b.ToTable("TB_EVENTO");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.LocalizacaoMoto", b =>
                {
                    b.Property<string>("IdMoto")
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<string>("LatitudeMoto")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)");

                    b.Property<string>("LongitudeMoto")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)");

                    b.HasKey("IdMoto");

                    b.ToTable("TB_LOCALIZACAO_MOTO");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.Moto", b =>
                {
                    b.Property<string>("IdMoto")
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<string>("ChassiMoto")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)");

                    b.Property<string>("IdPatio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("IotMoto")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)");

                    b.Property<string>("ModeloMoto")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("PatioIdPatio")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<string>("PlacaMoto")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("StatusMoto")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("IdMoto");

                    b.HasIndex("PatioIdPatio");

                    b.ToTable("TB_MOTO");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.Patio", b =>
                {
                    b.Property<string>("IdPatio")
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<bool>("EstruturaPatioCriada")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("IdFilial")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)");

                    b.HasKey("IdPatio");

                    b.ToTable("TB_PATIO");
                });

            modelBuilder.Entity("Motos.Domain.Entities.EventoMoto", b =>
                {
                    b.HasOne("Motos.Domain.Entitites.Evento", "Evento")
                        .WithMany("EventosMoto")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motos.Domain.Entitites.Moto", "Moto")
                        .WithMany("EventosMoto")
                        .HasForeignKey("IdMoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.EstruturaPatio", b =>
                {
                    b.HasOne("Motos.Domain.Entitites.Patio", "Patio")
                        .WithMany()
                        .HasForeignKey("IdPatio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.LocalizacaoMoto", b =>
                {
                    b.HasOne("Motos.Domain.Entitites.Moto", "Moto")
                        .WithOne("LocalizacaoMoto")
                        .HasForeignKey("Motos.Domain.Entitites.LocalizacaoMoto", "IdMoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.Moto", b =>
                {
                    b.HasOne("Motos.Domain.Entitites.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioIdPatio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.Evento", b =>
                {
                    b.Navigation("EventosMoto");
                });

            modelBuilder.Entity("Motos.Domain.Entitites.Moto", b =>
                {
                    b.Navigation("EventosMoto");

                    b.Navigation("LocalizacaoMoto")
                        .IsRequired();
                });

            modelBuilder.Entity("Motos.Domain.Entitites.Patio", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
